"""
AgentState — the central data structure flowing through the LangGraph.

Every node reads from and writes to this state.
LangGraph merges state updates automatically between node calls.
"""

from typing import TypedDict, Optional


class AgentState(TypedDict):
    # Core identifiers
    messages: list           # Full conversation history [{role, content}]
    session_id: str          # Active ChromaDB + Atlas session
    user_id: str             # Owner of the session
    subject_id: str          # Subject being studied

    # Routing
    intent: str              # rag_query | content_generation | study_planning | calendar_scheduling | session_end | chitchat

    # RAG pipeline
    retrieved_chunks: list   # Raw chunks from ChromaDB [{content, metadata, score}]
    chunk_confidence: float  # Top-1 similarity score from search_notes (0.0–1.0)

    # -------------------------------------------------------------------------
    # Sufficiency Judge pipeline (replaces Wikipedia fallback)
    # -------------------------------------------------------------------------
    judge_verdict: Optional[str]    # "SUFFICIENT" | "PARTIAL" | "INSUFFICIENT"
    judge_reason: Optional[str]     # Short explanation from the judge
    fallback_strategy: Optional[str]  # "gemini" | "tavily" — chosen by the user
    web_results: list               # Tavily search results [{title, url, content}]
    answer_source: Optional[str]    # "notes" | "gemini" | "tavily" | "notes+gemini" | "notes+tavily"

    # Tool outputs
    tool_results: dict       # Keyed by tool name: {\"gap_analysis\": {...}, ...}

    # Planning (for content_generation / study_planning intents)
    plan: list               # Ordered list of steps the planner chose

    # Final output
    response: str            # The final answer text assembled by SynthesisNode

    # Calendar (Day 5 — wired later, kept in state today)
    awaiting_confirmation: bool
    proposed_calendar_events: list

    # Study planning context — extracted from user message by StudyPlanBuilderNode
    exam_date: Optional[str]      # e.g. "2025-04-15" or "April 15"
    subject_name: Optional[str]   # Denormalized subject name (for tools that need it as string)
    topics: list                  # Topics provided by the user for this session

    # Session end pipeline (Day 7)
    transcript: list              # Full transcript passed in for evaluation
    evaluation: Optional[dict]    # Evaluator output: topics, depth, weak_moments, session_score
    session_summary: Optional[str]  # Human-readable summary generated by summary_node
